travis:
  secure:
    BINSTAR_TOKEN: auqI8Se5uiAXVqLCsNz8Ywhhg8QM3kUIP+p/DYIYo+xQFafg9Anz70rWh96YPDXa6rNxwld1hP9jLA+mARBe8/2ug1ouQ0mlni8ip6Y1U3Sy0af4f/3qoUTLmiGSjlPf3234Z32bW5L4Q2D4HQNJ/eUrbq7G71717JFZ07fIcNM/EcXnwxbLxPGWYxcmW+m3mb4dArSKJEZg5/Pi+rB6QQV8MeKNMUJWFiibkczO9eG12l92GBgYABIWb/bq7ncg2hYmrPxNIK0x3LOOWovhoH+72T1Sj4A3/zA6zhkUlNQUOg3xJIyGHdkuDcHVLUGORoBu3pdFM1lz7vdWZsxpAZLNHmrJuoB2WW0zFa3+3+P+Thkh/JmwvnmsuFw0XdjfPXCLCEhmEg9NOuT81q+CNG9IsgZdtUBzn64v4gBA/2i6FF7aK0ACD7vaIfME8ZRswP2ndsGMeUDkc9TvgPShVoWkalZiEu2rSlvrXfQacD6i5cRADqvhVLDiyYehdd0VRWS4gqI5q/vr2kBp0+NlHE0Y2ukLRqMfyZYLG2Z9N2h9TJKDUbL8bkByl/Q1lqxpagrOGYcKbNbvwTZUMzXf6x85uscBJrLIwY7G6YNWFpljS1fHT2wGDRtWy3FOpMumlHJs6HoO7zRXFJ/uv4c+nOW/kjNzUxHCL6lYYJwgbVQ=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
